services:
  ehailing-be:
    image: blueprintagency/ehailing-be:staging
    pull_policy: always
    container_name: ehailing-be
    restart: unless-stopped
    env_file: .env.ehailing-be
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ehailing-be.rule=Host(`ehailingapi.${BASE_DOMAIN}`)"
      - "traefik.http.routers.ehailing-be.entrypoints=websecure"
      - "traefik.http.routers.ehailing-be.tls.certresolver=letsencrypt"
      - "traefik.http.services.ehailing-be.loadbalancer.server.port=3000"
    networks:
      - proxy
      - ehailing-network

networks:
  proxy:
    external: true
  ehailing-network:
    name: ehailing-network
    driver: bridge
