#!/bin/bash
# Initial VPS setup. Everything a fresh host needs before deploy-infra.yml can
# reach it. Idempotent -- safe to re-run on an existing host.
#
# Usage: ssh root@<public-ip> 'TS_AUTHKEY=tskey-auth-... bash -s' < setup-vps.sh
#
# The auth key is generated by hand (Tailscale admin console -> Settings -> Keys);
# there is no Tailscale API token in .env. After this runs, go back to the console
# and DISABLE KEY EXPIRY on the new machine -- port 22 is closed to the internet on
# every host, so an expired key means console-only recovery. See CLAUDE.md.

set -euo pipefail

DEPLOY_USER="deploy"

echo "==> Updating system..."
apt-get update && apt-get upgrade -y

echo "==> Installing Docker..."
curl -fsSL https://get.docker.com | sh
apt-get install -y docker-compose-plugin

# Docker 29.x raises MinAPIVersion above 1.24, and Traefik v3.3 hardcodes 1.24 and
# ignores DOCKER_API_VERSION -- the daemon rejects it, Traefik loads ZERO routes,
# and every domain on the host 404s while the containers stay healthy. VPS1 sat
# like that for two months. The unit name differs for a snap install.
UNIT="docker.service"
systemctl list-units --plain --no-legend '*docker*' | grep -q 'snap.docker.dockerd' \
  && UNIT="snap.docker.dockerd.service"
DROPIN="/etc/systemd/system/${UNIT}.d/min-api.conf"
if [ ! -f "$DROPIN" ]; then
  echo "==> Pinning DOCKER_MIN_API_VERSION on ${UNIT}..."
  mkdir -p "$(dirname "$DROPIN")"
  printf '[Service]\nEnvironment="DOCKER_MIN_API_VERSION=1.24"\n' > "$DROPIN"
  systemctl daemon-reload
  systemctl restart "$UNIT"
fi

echo "==> Creating deploy user..."
id "$DEPLOY_USER" &>/dev/null || useradd -m -s /bin/bash "$DEPLOY_USER"
usermod -aG docker "$DEPLOY_USER"

echo "==> Setting up SSH for deploy user..."
mkdir -p /home/${DEPLOY_USER}/.ssh
cp /root/.ssh/authorized_keys /home/${DEPLOY_USER}/.ssh/ 2>/dev/null || true
chown -R ${DEPLOY_USER}:${DEPLOY_USER} /home/${DEPLOY_USER}/.ssh
chmod 700 /home/${DEPLOY_USER}/.ssh
chmod 600 /home/${DEPLOY_USER}/.ssh/authorized_keys 2>/dev/null || true

# CI rsyncs to /root/stacks/<stack>/ as deploy, which has no sudo. deploy must be
# able to traverse /root and own everything under stacks/, or the rsync fails.
echo "==> Preparing /root/stacks for ${DEPLOY_USER}..."
chmod 711 /root
mkdir -p /root/stacks
chown ${DEPLOY_USER}:${DEPLOY_USER} /root/stacks

echo "==> Installing Tailscale..."
command -v tailscale >/dev/null || curl -fsSL https://tailscale.com/install.sh | sh
if ! tailscale status >/dev/null 2>&1; then
  tailscale up --authkey "${TS_AUTHKEY:?set TS_AUTHKEY=tskey-auth-... -- see header}"
fi

systemctl enable --now "$UNIT"

echo
echo "==> Setup complete."
echo "    Docker:       $(docker --version)"
echo "    Tailscale IP: $(tailscale ip -4)"
echo
echo "    Still to do by hand (see the 'provision' skill):"
echo "      1. Tailscale console -> disable key expiry on this machine"
echo "      2. Firewall: 80 + 443 from any, 22 from 100.64.0.0/10 only"
echo "      3. GitHub Environment named after the host key, with TAILSCALE_HOST"
echo "      4. vps/hosts.json entry"
